### ISSUE TITLE
Wrong application name on Flathub

### ISSUE THREAD

**Issue by dphaldes** [flathub/org.kde.kclock#68]
![image](https://github.com/user-attachments/assets/d17fcec0-4498-44d3-8d9d-a1dacfffd316)

Not sure if this is a problem with flathub metadata or upstream issue.

**Comment by dphaldes** [comment]
Over on https://apps.kde.org/kclock/, It also says Clock. Is this supplied through appstream ?

**Comment by travier** [comment]
If you think this should be changed, you should file a bug upstream to bugs.kde.org.
